openapi: 3.0.0
info:
  version: "1.0.0"
  title: User security information
  description: Return the account security information for a user within Convergence infrastructure
paths:
  '/user/{user-name}/permissions':
    get:
      tags:
        - Step
      summary: User permissions
      description: Return roles and permissions of a user for both an specific operation or globally
      parameters:
        - name: user-name
          in: path
          description: ID of step to return
          required: true
          schema:
            type: string
        - name: operation-number
          in: query
          description: Operation number for which the permissions will be returned
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissionsSchema'
        '400':
          description: Bad request
        '401':
          description: Unathorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/fabs-co/idbschemas/master/global/baseapi.yaml#/error/base'
components:
  schemas:
    UserPermissionsSchema:
      type: object
      required:
        - fullName
        - email
        - permissions
        - roles
      properties:
        fullName:
          type: string
          description: return the fulle name of the given account
          example: John Doe
        email:
          type: string
          example: johndoe@iadb.org
          description: Email associated to the given account
        permissions:
          type: array
          description: List of permissions assigned to the given account
          items:
            type: string
            example: OperationData.Read
        roles:
          type: array
          example: 1
          description: List of roles assigned to the given account
          items:
            type: string
            example: Team Leader
